server:
  port: 8000
  servlet:
    context-path: /service

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/books"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: dacduy2005
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  accessKey: "WlioIGFI3ZMomFc8/aZP0/CMQgU6My4h/+v+wC3y9rQ="
  refreshKey: "YTOwveDw8h9T/nGjQvAnqiReaznqfMAn3cwmcoXRvfk="
  valid-duration: 3600 # in second
  refreshable-duration: 20000 #in seconds

